const imageLink = {
  background: require('./Start_Background.png'),
  colorLogo: require('./color-logo.png'),
  whiteLogo: require('./white-logo.png'),
  placeholder: require('./placeholder.jpeg'),
  onboardingImage1: require('./onboardingImage1.png'),
  onboardingImage2: require('./onboardingImage2.png'),
  onboardingImage3: require('./onboardingImage3.png'),
  drawerBg: require('./drawer-bg.png'),
  profileImage: require('./profileImage.png'),
  addIcon: require('./addIcon.png'),
  saveIcon: require('./save.png'),
  uploadImage: require('./uploadImage.png'),
  callPreviewBg: require('./callPreviewBg.png'),
  avatar: require('./avatar.png'),
  optionIcon: require('./optionIcon.png'),
  homeIcon: require('./homeIcon.png'),
  excelImage: require('./excelImage.png'),
  pdfIcon: require('./pdfIcon.png'),
  fireIcon: require('./fireIcon.png'),
  pet: require('./pets.png'),
  locationIcon: require('./locationIcon.png'),
  housesIcon: require('./houseIcon.png'),
  unitedStates: require('./unitedStates.png'),
  demoImage: require('./demoImage.png'),
  pinImage:require('./pinIcon.png'),
  maxicanFlag:require('./flagOfMaxico.png'),
  socialChanel:require('./socialChannel.png'),
};

export default imageLink;
