export const sliceName = {
  languageSlice: 'language-slice',
  themeSlice: 'theme-slice',
  authSlice: 'auth-slice',
  vehicleSlice: 'vehicles-slice',
  expenseSlice: 'expense-slice',
  generateMassiveChargesSlice: 'massive-charges-slice',
  petSlice: 'pet-slice',
  emergencyNumbers: 'emergencyNumbers',
  amenitiesSlice: 'amenities-slice',
  paymentsSlice: 'payments-slice',
  incidentsSlice: 'incidents-slice',
  visitsSlice: 'visits-slice',
  announcementsSlice: 'announcements-slice',
  documentsSlice: 'documents-slice',
  blacklistSlice: 'blacklist-slice',
  maintenanceSlice: 'maintenance-slice',
  surveysSlice: 'surveys-slice',
  servicesSlice: 'services-slice',
  rafflesSlice: 'raffles-slice',
  monthChargesSlice: 'monthCharges-slice',
  quotaConfigurationSlice: 'quotaConfiguration-slice', 
  saftyConfigurationSlice: 'saftyConfiguration-slice', 
  acceptCardSlice: 'acceptCard-slice',
  incomeExpenseClassifcationSlice: 'expenseClassifcation-slice', 
  otherIncomeSlice: 'otherIncome-slice',
  saftyReportSlice: 'saftyReport-slice',
  reportActivitySlice: 'reportActivity-slice',
  expenseTemplateSlice: 'expenseTemplate-slice',
  userSlice: 'user-slice',
  frequentVisitSlice: 'frequentVisit-slice',
  chatsSlice: 'chats-slice',
  accountStatusSlice: 'accountStatus-slice',
  debtorsReportSlice: 'debtors-report-slice',
  bookingSlice: 'booking-slice',
  AssistanceSlice: 'Assistance-slice',
  Colonyslice:"Colony-slice",
  DeviceSlice:"ActiveDevice-slice",
  AccessControlSlice:'AcessControl-slice',
  AccessTagCardSlice:'AccessTagCard-slice',
  QrReaderSlice:"QrReader-slice",
  SmartDoorSlice:"smartDoor-slice",
  VirtualPhoneSlice:"VirtualPhone-slice",
  Surveillance:"Surveillance-slice",
  SocialChannel:'SocialChannel=slice',
  Siren:"Siren-slice",
  residentVig:'Resident-Vig',
  AssistSlice:'Assist-slice',
  EventualVisitSlice:'EventualVisit-Slice',
  DismissVisitSlice:'DismissVisit-Slice'
};
